# Each person: id, name, aka, desc, pats (regexes in WEB spelling), refs (None = every match in Acts–Jude;
# otherwise list of "BOOK c:v", "BOOK c:v-v" or (range, pattern-override)), gospels flag.
# kind: "associate" (default) or "official" — Roman/Herodian/Nabataean state figures who
# interact with the movement only as rulers or judges, never as believers or co-workers.
# Officials are excluded from the "Across books" grid: a governor named once in a letter's
# aside is not a cross-corpus associate, even when the attestation math says "both".
def P(id, name, desc, pats, refs=None, aka=None, gospels=False, exclude=None, kind="associate"):
    return dict(id=id, name=name, desc=desc, pats=pats, refs=refs, aka=aka or [], gospels=gospels, exclude=exclude or [], kind=kind)

PEOPLE = [
 # ---- the major figures
 P("paul","Paul","Apostle to the nations; called Saul until Acts 13:9. Named as sender of thirteen letters and once by 2 Peter.",[r"\bPaul\b",r"\bSaul\b"],aka=["Saul"],exclude=["ACT 13:21"]),
 P("peter","Peter","Simon son of Jonah, first among the Twelve. Paul usually calls him by the Aramaic form Cephas; James calls him Simeon at the Jerusalem council.",[r"Simon, who (?:is|was) (?:also )?called Peter",r"Simon Peter",r"\bPeter\b",r"\bCephas\b",r"Simeon(?= has reported)"],refs=None,aka=["Cephas","Simon","Simeon"],gospels=True),
 P("john_zeb","John son of Zebedee","One of the Twelve; Peter's companion in the early chapters of Acts and one of the three 'pillars' Paul met in Jerusalem.",[r"\bJohn\b"],refs=["ACT 1:13","ACT 3:1-11","ACT 4:7-19","ACT 8:14","ACT 12:2","GAL 2:9"],gospels=True),
 P("james_lord","James the Lord's brother","Leader of the Jerusalem assembly after Peter's departure; presides at the council of Acts 15. Named as author of the letter of James and as brother of Jude.",[r"\bJames\b"],refs=["ACT 12:17","ACT 15:13","ACT 21:18","1CO 15:7","GAL 1:19","GAL 2:9","GAL 2:12","JAM 1:1","JUD 1:1"],gospels=True),
 P("barnabas","Barnabas","Levite from Cyprus, originally Joseph (WEB: Joses). Introduces Saul at Jerusalem, leads the first mission with him, then parts from him over Mark, his cousin.",[r"\bBarnabas\b",r"\bJoses\b"],aka=["Joseph","Joses"]),
 P("timothy","Timothy","From Lystra, son of a Jewish mother and Greek father. Paul's closest co-worker: co-sender of six letters, addressee of two, and the only contemporary named in Hebrews.",[r"\bTimothy\b"]),
 P("silas","Silas","Jerusalem prophet sent to Antioch with the council's letter; Paul's partner on the second journey. The letters use the Latin form Silvanus; 1 Peter names him as its carrier or secretary.",[r"\bSilas\b",r"\bSilvanus\b"],aka=["Silvanus"]),
 P("mark","John Mark","Son of Mary of Jerusalem and cousin of Barnabas. Leaves the first mission at Perga; later with Paul (Colossians, Philemon), wanted by him (2 Timothy), and 'my son' to Peter.",[r"John,? who was called Mark",r"\bMark\b"],refs=["ACT 12:12","ACT 12:25",("ACT 13:5",r"\bJohn\b"),("ACT 13:13",r"\bJohn\b"),"ACT 15:37","ACT 15:39","COL 4:10","2TI 4:11","PHM 1:24","1PE 5:13"],aka=["John","Mark"]),
 P("titus","Titus","Uncircumcised Greek taken to Jerusalem as a test case; Paul's envoy to Corinth for the collection; left in Crete. Never named in Acts.",[r"\bTitus\b"]),
 P("apollos","Apollos","Alexandrian Jew, eloquent in the Scriptures, instructed by Priscilla and Aquila at Ephesus and active at Corinth, where a party claimed his name.",[r"\bApollos\b"]),
 P("aquila","Aquila","Jew from Pontus, tentmaker, expelled from Rome under Claudius. Hosts Paul at Corinth and, with his wife, a house assembly in Ephesus and Rome.",[r"\bAquila\b"]),
 P("prisca","Prisca","Wife of Aquila, named before him in four of six mentions. Acts uses the diminutive Priscilla; Paul writes Prisca.",[r"\bPriscilla\b",r"\bPrisca\b"],aka=["Priscilla"]),
 P("luke","Luke","'The beloved physician', with Paul in Colossians, Philemon and 2 Timothy. Tradition makes him the author of Luke–Acts, where he is never named.",[r"\bLuke\b"]),

 # ---- Acts 1: the Twelve and the upper room
 P("theophilus","Theophilus","Dedicatee of Luke and Acts.",[r"\bTheophilus\b"],gospels=True),
 P("james_zeb","James son of Zebedee","One of the Twelve, brother of John; killed with the sword by Herod Agrippa.",[r"(?<=John, )James",r"\bJames\b"],refs=[("ACT 1:13",r"(?<=John, )James"),"ACT 12:2"],gospels=True),
 P("andrew","Andrew","One of the Twelve, Peter's brother.",[r"\bAndrew\b"],gospels=True),
 P("philip_ap","Philip the apostle","One of the Twelve; distinct from Philip the evangelist of Acts 6–8.",[r"\bPhilip\b"],refs=["ACT 1:13"],gospels=True),
 P("thomas","Thomas","One of the Twelve.",[r"\bThomas\b"],gospels=True),
 P("bartholomew","Bartholomew","One of the Twelve.",[r"\bBartholomew\b"],gospels=True),
 P("matthew","Matthew","One of the Twelve.",[r"\bMatthew\b"],gospels=True),
 P("james_alph","James son of Alphaeus","One of the Twelve.",[r"James the son of Alphaeus"],refs=["ACT 1:13"],gospels=True),
 P("simon_zealot","Simon the Zealot","One of the Twelve.",[r"Simon the Zealot"],refs=["ACT 1:13"],gospels=True),
 P("judas_james","Judas son of James","One of the Twelve in Luke's list.",[r"Judas the son of James"],refs=["ACT 1:13"],gospels=True),
 P("judas_isc","Judas Iscariot","The betrayer, whose place among the Twelve is filled in Acts 1.",[r"\bJudas\b"],refs=["ACT 1:16","ACT 1:25"],gospels=True),
 P("mary_mother","Mary the mother of Jesus","Present with the brothers of Jesus in the upper room; her last appearance in the New Testament.",[r"\bMary\b"],refs=["ACT 1:14"],gospels=True),
 P("joseph_barsabbas","Joseph Barsabbas Justus","Candidate, with Matthias, to replace Judas.",[r"Joseph called Barsabbas, who was also called Justus"],refs=["ACT 1:23"],aka=["Justus"]),
 P("matthias","Matthias","Chosen by lot to be numbered with the eleven.",[r"\bMatthias\b"]),
 P("john_baptist","John the Baptizer","Recalled in the speeches of Acts; his disciples are still found at Ephesus in Acts 19.",[r"\bJohn\b"],refs=["ACT 1:5","ACT 1:22","ACT 10:37","ACT 11:16","ACT 13:24-25","ACT 18:25","ACT 19:3-4"],gospels=True),
 P("pilate","Pontius Pilate","Prefect of Judea. Named in three Acts speeches and once in 1 Timothy, the only mention of him in any letter.",[r"Pontius Pilate",r"\bPilate\b"],gospels=True,kind="official"),
 P("herod_antipas","Herod the tetrarch","Antipas, ruler of Galilee; named in the believers' prayer and as foster brother of Manaen.",[r"\bHerod\b"],refs=["ACT 4:27","ACT 13:1"],gospels=True,kind="official"),

 # ---- Acts 4–9
 P("annas","Annas","High priest, head of the family before whom Peter and John are examined.",[r"\bAnnas\b"],gospels=True),
 P("caiaphas","Caiaphas","Of the high-priestly family.",[r"\bCaiaphas\b"],gospels=True),
 P("john_priest","John of the high-priestly family","Present at the hearing of Peter and John; otherwise unknown.",[r"\bJohn\b"],refs=[("ACT 4:6",r"(?<=Caiaphas, )John")]),
 P("alexander_priest","Alexander of the high-priestly family","Present at the hearing of Peter and John; otherwise unknown.",[r"\bAlexander\b"],refs=["ACT 4:6"]),
 P("ananias_jer","Ananias of Jerusalem","Husband of Sapphira; falls dead after keeping back part of a sale price.",[r"\bAnanias\b"],refs=["ACT 5:1-5"]),
 P("sapphira","Sapphira","Wife of Ananias of Jerusalem.",[r"\bSapphira\b"]),
 P("gamaliel","Gamaliel","Pharisee and teacher of the law who counsels restraint in the council; Paul claims him as his teacher.",[r"\bGamaliel\b"]),
 P("theudas","Theudas","Failed insurgent cited by Gamaliel.",[r"\bTheudas\b"]),
 P("judas_galilee","Judas of Galilee","Leader of the revolt at the census, cited by Gamaliel.",[r"Judas of Galilee"],refs=["ACT 5:37"]),
 P("stephen","Stephen","First of the Seven and first martyr; Paul recalls his death in Acts 22.",[r"\bStephen\b"]),
 P("philip_evan","Philip the evangelist","One of the Seven; preaches in Samaria and to the Ethiopian official; hosts Paul at Caesarea with his four daughters.",[r"\bPhilip\b"],refs=["ACT 6:5","ACT 8:5-40","ACT 21:8"]),
 P("prochorus","Prochorus","One of the Seven.",[r"\bProchorus\b"]),
 P("nicanor","Nicanor","One of the Seven.",[r"\bNicanor\b"]),
 P("timon","Timon","One of the Seven.",[r"\bTimon\b"]),
 P("parmenas","Parmenas","One of the Seven.",[r"\bParmenas\b"]),
 P("nicolaus","Nicolaus of Antioch","One of the Seven, a proselyte.",[r"\bNicolaus\b"]),
 P("simon_magus","Simon the sorcerer","Samaritan magician who offers money for the power to confer the Spirit.",[r"\bSimon\b"],refs=["ACT 8:9-24"]),
 P("candace","Candace","Title of the queen of the Ethiopians, whose treasurer Philip baptizes.",[r"\bCandace\b"]),
 P("ananias_dam","Ananias of Damascus","Disciple sent to restore Saul's sight and baptize him.",[r"\bAnanias\b"],refs=["ACT 9:10-17","ACT 22:12"]),
 P("judas_damascus","Judas of Straight Street","Saul's host in Damascus (WEB: Judah).",[r"\bJudah\b"],refs=["ACT 9:11"],aka=["Judah"]),
 P("aeneas","Aeneas","Paralyzed man healed by Peter at Lydda.",[r"\bAeneas\b"]),
 P("tabitha","Tabitha","Disciple at Joppa, raised by Peter; Dorcas in Greek.",[r"\bTabitha\b",r"\bDorcas\b"],aka=["Dorcas"]),
 P("simon_tanner","Simon the tanner","Peter's host at Joppa.",[r"Simon,? a tanner",r"Simon the tanner",r"Simon’s house",r"\bSimon\b"],refs=[("ACT 9:43",r"\bSimon\b"),("ACT 10:6",r"\bSimon\b"),("ACT 10:17",r"Simon’s"),("ACT 10:32",r"(?<=named )Simon")]),

 # ---- Acts 10–15
 P("cornelius","Cornelius","Centurion of the Italian Regiment at Caesarea; first Gentile household baptized.",[r"\bCornelius\b"]),
 P("agabus","Agabus","Prophet from Judea; foretells the famine and, later, Paul's arrest.",[r"\bAgabus\b"]),
 P("claudius_emp","Claudius","Emperor (41–54); the famine and the expulsion of Jews from Rome are dated to his reign.",[r"\bClaudius\b"],refs=["ACT 11:28","ACT 18:2"],kind="official"),
 P("herod_agrippa1","Herod Agrippa I","King of Judea (41–44); kills James, imprisons Peter, dies at Caesarea.",[r"\bHerod\b"],refs=["ACT 12:1-23"],kind="official"),
 P("mary_mark","Mary of Jerusalem","Mother of John Mark; the assembly prays in her house.",[r"\bMary\b"],refs=["ACT 12:12"]),
 P("rhoda","Rhoda","Servant girl who answers Peter's knock.",[r"\bRhoda\b"]),
 P("blastus","Blastus","Chamberlain of Herod Agrippa.",[r"\bBlastus\b"]),
 P("simeon_niger","Simeon called Niger","Prophet or teacher at Antioch.",[r"Simeon who was called Niger"],refs=["ACT 13:1"],aka=["Niger"]),
 P("lucius_cyrene","Lucius of Cyrene","Prophet or teacher at Antioch.",[r"Lucius of Cyrene"],refs=["ACT 13:1"]),
 P("manaen","Manaen","Prophet or teacher at Antioch, brought up with Herod the tetrarch.",[r"\bManaen\b"]),
 P("sergius_paulus","Sergius Paulus","Proconsul of Cyprus who believes.",[r"Sergius Paulus"]),
 P("elymas","Bar Jesus","Jewish sorcerer attached to the proconsul of Cyprus; also called Elymas.",[r"Bar Jesus",r"\bElymas\b"],aka=["Elymas"]),
 P("judas_barsabbas","Judas Barsabbas","Jerusalem prophet sent with Silas to carry the council's letter to Antioch.",[r"\bJudas\b"],refs=["ACT 15:22","ACT 15:27","ACT 15:32"]),

 # ---- Acts 16–20
 P("lydia","Lydia","Seller of purple from Thyatira; first convert at Philippi and host of the mission.",[r"\bLydia\b"]),
 P("jason_thess","Jason of Thessalonica","Paul's host, dragged before the city rulers and made to post bond.",[r"\bJason\b"],refs=["ACT 17:5-9"]),
 P("dionysius","Dionysius the Areopagite","Member of the Areopagus court who believes at Athens.",[r"\bDionysius\b"]),
 P("damaris","Damaris","Woman who believes at Athens.",[r"\bDamaris\b"]),
 P("justus_corinth","Justus of Corinth","God-fearer next door to the synagogue, whose house Paul uses. Other manuscripts read Titius Justus; WEB follows the Majority Text.",[r"\bJustus\b"],refs=["ACT 18:7"],aka=["Titius Justus"]),
 P("crispus","Crispus","Ruler of the Corinthian synagogue who believes with his household; one of the few Paul baptized himself.",[r"\bCrispus\b"]),
 P("gallio","Gallio","Proconsul of Achaia who dismisses the case against Paul; the Delphi inscription fixes his term near 51–52.",[r"\bGallio\b"],kind="official"),
 P("sosthenes_acts","Sosthenes the synagogue ruler","Beaten before Gallio's judgment seat at Corinth.",[r"\bSosthenes\b"],refs=["ACT 18:17"]),
 P("tyrannus","Tyrannus","Owner or teacher of the lecture hall Paul uses for two years at Ephesus.",[r"\bTyrannus\b"]),
 P("sceva","Sceva","Jewish chief priest whose seven sons attempt an exorcism in Jesus' name.",[r"\bSceva\b"]),
 P("erastus_acts","Erastus the assistant","Sent ahead into Macedonia with Timothy; 2 Timothy leaves an Erastus at Corinth, which may point instead to the city treasurer.",[r"\bErastus\b"],refs=["ACT 19:22","2TI 4:20"]),
 P("demetrius_silver","Demetrius the silversmith","Maker of Artemis shrines who stirs up the riot at Ephesus.",[r"\bDemetrius\b"],refs=["ACT 19:24","ACT 19:38"]),
 P("gaius_mac","Gaius the Macedonian","Travel companion of Paul seized in the Ephesian riot.",[r"\bGaius\b"],refs=["ACT 19:29"]),
 P("aristarchus","Aristarchus","Macedonian from Thessalonica: seized at Ephesus, delegate on the collection journey, aboard the ship to Rome, and Paul's 'fellow prisoner'.",[r"\bAristarchus\b"]),
 P("alexander_eph","Alexander of Ephesus","Jew put forward to address the mob during the riot.",[r"\bAlexander\b"],refs=["ACT 19:33"]),
 P("sopater","Sopater of Beroea","Delegate accompanying Paul toward Jerusalem.",[r"\bSopater\b"]),
 P("secundus","Secundus","Thessalonian delegate accompanying Paul toward Jerusalem.",[r"\bSecundus\b"]),
 P("gaius_derbe","Gaius of Derbe","Delegate accompanying Paul toward Jerusalem.",[r"\bGaius\b"],refs=["ACT 20:4"]),
 P("tychicus","Tychicus","Delegate from Asia; later the carrier of Colossians and Ephesians and Paul's relief for Titus and Timothy.",[r"\bTychicus\b"]),
 P("trophimus","Trophimus","Ephesian Gentile whose presence in Jerusalem sparks Paul's arrest; left sick at Miletus in 2 Timothy.",[r"\bTrophimus\b"]),
 P("eutychus","Eutychus","Young man who falls from the window at Troas.",[r"\bEutychus\b"]),

 # ---- Acts 21–28
 P("mnason","Mnason of Cyprus","Early disciple with whom Paul's party lodges.",[r"\bMnason\b"]),
 P("claudius_lysias","Claudius Lysias","Tribune commanding the Jerusalem garrison; his letter to Felix is quoted.",[r"Claudius Lysias",r"\bLysias\b"],refs=["ACT 23:26","ACT 24:22"],kind="official"),
 P("ananias_hp","Ananias the high priest","Orders Paul struck; leads the prosecution before Felix.",[r"\bAnanias\b"],refs=["ACT 23:2","ACT 24:1"]),
 P("tertullus","Tertullus","Orator retained to prosecute Paul.",[r"\bTertullus\b"]),
 P("felix","Felix","Governor of Judea who keeps Paul in custody two years.",[r"\bFelix\b"],kind="official"),
 P("drusilla","Drusilla","Jewish wife of Felix, daughter of Agrippa I.",[r"\bDrusilla\b"],kind="official"),
 P("festus","Porcius Festus","Felix's successor; sends Paul to Caesar.",[r"Porcius Festus",r"\bFestus\b"],kind="official"),
 P("agrippa2","Agrippa II","King, son of Agrippa I; hears Paul's defense at Caesarea.",[r"\bAgrippa\b"],kind="official"),
 P("bernice","Bernice","Sister of Agrippa II and of Drusilla.",[r"\bBernice\b"],kind="official"),
 P("julius","Julius","Centurion of the Augustan band who escorts Paul to Rome.",[r"\bJulius\b"]),
 P("publius","Publius","Chief man of Malta, whose father Paul heals.",[r"\bPublius\b"]),

 # ---- Romans 16
 P("phoebe","Phoebe","Servant (diakonos) of the assembly at Cenchreae and Paul's patron; presumably the carrier of Romans.",[r"\bPhoebe\b"]),
 P("epaenetus","Epaenetus","'First fruits' of Paul's mission (WEB: of Achaia; other manuscripts: of Asia).",[r"\bEpaenetus\b"]),
 P("mary_rome","Mary of Rome","'Labored much for us.'",[r"\bMary\b"],refs=["ROM 16:6"]),
 P("andronicus","Andronicus","Paul's kinsman and fellow prisoner, 'notable among the apostles', in Christ before Paul.",[r"\bAndronicus\b"]),
 P("junia","Junia","Named with Andronicus as kin, fellow prisoner and 'notable among the apostles'.",[r"\bJunia\b"]),
 P("amplias","Amplias","'My beloved in the Lord.' Ampliatus in other manuscripts.",[r"\bAmplias\b"],aka=["Ampliatus"]),
 P("urbanus","Urbanus","'Our fellow worker in Christ.'",[r"\bUrbanus\b"]),
 P("stachys","Stachys","'My beloved.'",[r"\bStachys\b"]),
 P("apelles","Apelles","'The approved in Christ.'",[r"\bApelles\b"]),
 P("aristobulus","Aristobulus","Head of a household some of whose members are greeted; not himself greeted.",[r"\bAristobulus\b"]),
 P("herodion","Herodion","Paul's kinsman.",[r"\bHerodion\b"]),
 P("narcissus","Narcissus","Head of a household some of whose members are 'in the Lord'; not himself greeted.",[r"\bNarcissus\b"]),
 P("tryphaena","Tryphaena","'Labors in the Lord', with Tryphosa.",[r"\bTryphaena\b"]),
 P("tryphosa","Tryphosa","'Labors in the Lord', with Tryphaena.",[r"\bTryphosa\b"]),
 P("persis","Persis","'The beloved, who labored much in the Lord.'",[r"\bPersis\b"]),
 P("rufus","Rufus","'Chosen in the Lord'; his mother was a mother to Paul. Often linked with the Rufus of Mark 15:21, son of Simon of Cyrene.",[r"\bRufus\b"]),
 P("asyncritus","Asyncritus","Greeted with a group of brothers.",[r"\bAsyncritus\b"]),
 P("phlegon","Phlegon","Greeted with a group of brothers.",[r"\bPhlegon\b"]),
 P("hermas","Hermas","Greeted with a group of brothers.",[r"\bHermas\b"]),
 P("patrobas","Patrobas","Greeted with a group of brothers.",[r"\bPatrobas\b"]),
 P("hermes","Hermes","Greeted with a group of brothers.",[r"\bHermes\b"],refs=["ROM 16:14"]),
 P("philologus","Philologus","Greeted with Julia and 'all the saints with them'.",[r"\bPhilologus\b"]),
 P("julia","Julia","Greeted with Philologus.",[r"\bJulia\b"]),
 P("nereus","Nereus","Greeted with his sister.",[r"\bNereus\b"]),
 P("olympas","Olympas","Greeted with Philologus' group.",[r"\bOlympas\b"]),
 P("lucius_rom","Lucius","Paul's kinsman, sending greetings from Corinth.",[r"\bLucius\b"],refs=["ROM 16:21"]),
 P("jason_rom","Jason","Paul's kinsman, sending greetings from Corinth.",[r"\bJason\b"],refs=["ROM 16:21"]),
 P("sosipater","Sosipater","Paul's kinsman, sending greetings from Corinth.",[r"\bSosipater\b"]),
 P("tertius","Tertius","The scribe who wrote Romans down and greets in his own voice.",[r"\bTertius\b"]),
 P("gaius_corinth","Gaius of Corinth","Paul's host and host of the whole assembly; one of the few Paul baptized himself.",[r"\bGaius\b"],refs=["ROM 16:23","1CO 1:14"]),
 P("erastus_rom","Erastus the city treasurer","Treasurer (oikonomos) of Corinth. A pavement inscription at Corinth names an aedile Erastus.",[r"\bErastus\b"],refs=["ROM 16:23"]),
 P("quartus","Quartus","'The brother.'",[r"\bQuartus\b"]),

 # ---- Corinthians, Galatians
 P("sosthenes_cor","Sosthenes the brother","Co-sender of 1 Corinthians.",[r"\bSosthenes\b"],refs=["1CO 1:1"]),
 P("chloe","Chloe","Her people report the Corinthian factions to Paul.",[r"\bChloe\b"]),
 P("stephanas","Stephanas","His household was the first fruits of Achaia; visits Paul at Ephesus.",[r"\bStephanas\b"]),
 P("fortunatus","Fortunatus","Arrives with Stephanas from Corinth.",[r"\bFortunatus\b"]),
 P("achaicus","Achaicus","Arrives with Stephanas from Corinth.",[r"\bAchaicus\b"]),
 P("aretas","Aretas","Nabataean king Aretas IV, whose governor guarded Damascus to seize Paul.",[r"\bAretas\b"],kind="official"),

 # ---- Philippians, Colossians, Philemon
 P("epaphroditus","Epaphroditus","Envoy of the Philippians who carries their gift, falls gravely ill, and is sent home.",[r"\bEpaphroditus\b"]),
 P("euodia","Euodia","Co-worker at Philippi, urged to agree with Syntyche.",[r"\bEuodia\b"]),
 P("syntyche","Syntyche","Co-worker at Philippi, urged to agree with Euodia.",[r"\bSyntyche\b"]),
 P("clement","Clement","Fellow worker at Philippi. Later tradition identified him with Clement of Rome.",[r"\bClement\b"]),
 P("epaphras","Epaphras","Colossian who founded the assemblies of the Lycus valley; Paul's 'fellow prisoner' in Philemon.",[r"\bEpaphras\b"]),
 P("onesimus","Onesimus","Philemon's slave, sent back 'no longer as a slave'; travels with Tychicus to Colossae.",[r"\bOnesimus\b"]),
 P("jesus_justus","Jesus called Justus","One of Paul's three Jewish fellow workers named in Colossians.",[r"Jesus who is called Justus"],refs=["COL 4:11"],aka=["Justus"]),
 P("demas","Demas","Fellow worker in Colossians and Philemon; in 2 Timothy he has 'loved this present world' and left.",[r"\bDemas\b"]),
 P("nymphas","Nymphas","Host of a house assembly at Laodicea. WEB reads a man's name and 'his house'; other manuscripts read Nympha and 'her house'.",[r"\bNymphas\b"],aka=["Nympha"]),
 P("archippus","Archippus","'Fellow soldier' in Philemon's house; told in Colossians to fulfil his ministry.",[r"\bArchippus\b"]),
 P("philemon","Philemon","Householder and host of an assembly; owner of Onesimus.",[r"\bPhilemon\b"]),
 P("apphia","Apphia","Addressed with Philemon, probably his wife.",[r"\bApphia\b"]),

 # ---- Pastorals
 P("hymenaeus","Hymenaeus","Teacher Paul 'delivered to Satan'; says the resurrection is already past.",[r"\bHymenaeus\b"]),
 P("alexander_tim","Alexander (1 Timothy)","Delivered to Satan with Hymenaeus.",[r"\bAlexander\b"],refs=["1TI 1:20"]),
 P("alexander_smith","Alexander the coppersmith","'Did much evil to me.'",[r"\bAlexander\b"],refs=["2TI 4:14"]),
 P("lois","Lois","Timothy's grandmother.",[r"\bLois\b"]),
 P("eunice","Eunice","Timothy's mother; Acts 16:1 mentions her as a believing Jewish woman without naming her.",[r"\bEunice\b"]),
 P("phygelus","Phygelus","Among those in Asia who turned away from Paul.",[r"\bPhygelus\b"]),
 P("hermogenes","Hermogenes","Among those in Asia who turned away from Paul.",[r"\bHermogenes\b"]),
 P("onesiphorus","Onesiphorus","Sought Paul out in Rome and was not ashamed of his chain; his household is greeted.",[r"\bOnesiphorus\b"]),
 P("philetus","Philetus","Named with Hymenaeus as teaching that the resurrection is past.",[r"\bPhiletus\b"]),
 P("crescens","Crescens","Gone to Galatia.",[r"\bCrescens\b"]),
 P("carpus","Carpus","Holds Paul's cloak, books and parchments at Troas.",[r"\bCarpus\b"]),
 P("eubulus","Eubulus","Sends greetings to Timothy.",[r"\bEubulus\b"]),
 P("pudens","Pudens","Sends greetings to Timothy.",[r"\bPudens\b"]),
 P("linus","Linus","Sends greetings to Timothy. Irenaeus identifies him with the first bishop of Rome after the apostles.",[r"\bLinus\b"]),
 P("claudia","Claudia","Sends greetings to Timothy.",[r"\bClaudia\b"]),
 P("artemas","Artemas","Possible replacement for Titus in Crete.",[r"\bArtemas\b"]),
 P("zenas","Zenas the lawyer","Travelling with Apollos; Titus is to speed them on.",[r"\bZenas\b"]),

 # ---- Catholic letters
 P("gaius_3jn","Gaius (3 John)","Addressee of 3 John, praised for hospitality to travelling brothers.",[r"\bGaius\b"],refs=["3JO 1:1"]),
 P("diotrephes","Diotrephes","'Loves to be first'; refuses the elder's envoys.",[r"\bDiotrephes\b"]),
 P("demetrius_3jn","Demetrius (3 John)","Commended by all; probably the carrier of 3 John.",[r"\bDemetrius\b"],refs=["3JO 1:12"]),
 P("jude","Jude","Names himself 'brother of James'; usually identified with Judas the brother of Jesus (Mark 6:3).",[r"\bJude\b",r"\bJudah\b"],refs=["JUD 1:1"]),
]

# Conjectural identifications between separately listed entries.
LINKS = [
 ("sopater","sosipater","probable","Sosipater is the fuller form of Sopater. Romans was written from Greece just before the journey of Acts 20:4, on which Sopater sets out with Paul."),
 ("jason_thess","jason_rom","possible","Both are associates of Paul in the Aegean mission, and Romans 16:21 places its Jason beside a probable Beroean. The name is common."),
 ("lucius_cyrene","lucius_rom","possible","Same name, both in Paul's circle; nothing else connects them."),
 ("lucius_rom","luke","possible","Loukas is a short form of Lucius, a conjecture known to Origen. Against it: Lucius is Paul's 'kinsman', while Colossians 4:11–14 lists Luke apart from the fellow workers 'of the circumcision'."),
 ("sosthenes_acts","sosthenes_cor","possible","If the synagogue ruler beaten at Corinth later believed, he would be a natural co-sender of a letter to Corinth. Acts does not say he did."),
 ("erastus_acts","erastus_rom","possible","Both are tied to Corinth, but a sitting city treasurer is an unlikely travelling assistant. 2 Timothy 4:20 could belong to either."),
 ("gaius_mac","gaius_derbe","possible","A Western reading at Acts 20:4 makes Gaius a man of Doberus in Macedonia, which would merge the two; the usual text keeps them apart."),
 ("gaius_corinth","justus_corinth","possible","E. J. Goodspeed proposed one Corinthian householder named Gaius Titius Justus. It depends on the reading 'Titius Justus', which WEB does not print."),
 ("alexander_tim","alexander_smith","probable","Both are opponents of Paul within the Pastorals, connected with Ephesus."),
 ("alexander_eph","alexander_smith","possible","Both are at Ephesus; the Acts figure is a Jewish spokesman, not evidently a believer or a metalworker."),
 ("epaphras","epaphroditus","possible","Epaphras is a short form of Epaphroditus, but one belongs to Colossae and the other to Philippi; most keep them distinct."),
]
